-- Additive/non-destructive: preserve all existing audit records and the acceptance event.
BEGIN;

ALTER TYPE "AuditAction" ADD VALUE 'USUARIO_CADASTRADO';
ALTER TYPE "AuditAction" ADD VALUE 'LOGIN_SUCESSO';
ALTER TYPE "AuditAction" ADD VALUE 'LOGIN_FALHA';
ALTER TYPE "AuditAction" ADD VALUE 'DIAGNOSTICO_INICIADO';
ALTER TYPE "AuditAction" ADD VALUE 'DIAGNOSTICO_FINALIZADO';
ALTER TYPE "AuditAction" ADD VALUE 'QUESTAO_CRIADA';
ALTER TYPE "AuditAction" ADD VALUE 'QUESTAO_ATUALIZADA';
ALTER TYPE "AuditAction" ADD VALUE 'QUESTAO_EXCLUIDA';

ALTER TABLE "AuditLog"
  ALTER COLUMN "userId" DROP NOT NULL,
  ALTER COLUMN "termsVersion" DROP NOT NULL,
  ALTER COLUMN "privacyVersion" DROP NOT NULL,
  ADD COLUMN "resourceId" TEXT;

COMMIT;
