import { useState } from 'react';

const api = import.meta.env.VITE_API_URL ?? 'http://localhost:3333';

export function AuthGate() {
  const [mode, setMode] = useState<'login' | 'register' | 'confirm'>('login');
  const [nome, setNome] = useState(''); const [email, setEmail] = useState(''); const [senha, setSenha] = useState(''); const [confirmacaoSenha, setConfirmacaoSenha] = useState(''); const [codigo, setCodigo] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const post = async (path: string, body: object) => { const response = await fetch(`${api}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.message ?? 'Nao foi possivel concluir a operacao.'); return data; };
  const submit = async () => { setLoading(true); setError(''); try { if (mode === 'register') { await post('/auth/register', { nome, email, senha, confirmacaoSenha }); setMode('confirm'); } else if (mode === 'confirm') { await post('/auth/confirm-email', { email, codigo }); setMode('login'); } else { const login = await post('/auth/login', { email, senha }); const response = await fetch(`${api}/auth/session`, { headers: { Authorization: `Bearer ${login.token}` } }); const session = await response.json(); if (!response.ok) throw new Error(session.message ?? 'Sessao invalida.'); sessionStorage.setItem('jurissim_token', login.token); sessionStorage.setItem('jurissim_next_step', session.nextStep); window.location.reload(); } } catch (cause) { setError(cause instanceof Error ? cause.message : 'Erro inesperado.'); } finally { setLoading(false); } };
  return <main className="landing"><section className="pitch"><div className="brand"><b>⚖</b><span><strong>JurisSim</strong><small>Plataforma adaptativa para o Exame da OAB.</small></span></div><div className="pitch-text"><p>DIAGNOSTICO INTELIGENTE</p><h1>Prepare-se para a OAB <em>no seu ritmo.</em></h1></div></section><section className="entry"><div><p className="gold">JURISSIM · ACESSO</p><h2>{mode === 'register' ? 'Crie sua conta' : mode === 'confirm' ? 'Confirme seu e-mail' : 'Entre para estudar'}</h2><article className="start-card auth-card">{mode === 'register' && <input placeholder="Nome" value={nome} onChange={event => setNome(event.target.value)} />}<input type="email" placeholder="E-mail" value={email} onChange={event => setEmail(event.target.value)} />{mode !== 'confirm' && <input type="password" placeholder="Senha" value={senha} onChange={event => setSenha(event.target.value)} />}{mode === 'register' && <input type="password" placeholder="Confirme a senha" value={confirmacaoSenha} onChange={event => setConfirmacaoSenha(event.target.value)} />}{mode === 'confirm' && <input inputMode="numeric" maxLength={6} placeholder="Codigo de 6 digitos" value={codigo} onChange={event => setCodigo(event.target.value)} />}<button className="primary" disabled={loading} onClick={submit}>{loading ? 'Aguarde...' : mode === 'register' ? 'Cadastrar' : mode === 'confirm' ? 'Confirmar e-mail' : 'Entrar'}</button>{error && <small className="error">{error}</small>}</article>{mode !== 'confirm' && <button className="link-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Ainda nao tenho cadastro' : 'Ja tenho uma conta'}</button>}</div></section></main>;
}
