import { useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { AuthGate } from './auth-gate';

const api = import.meta.env.VITE_API_URL ?? 'http://localhost:3333';
// TESTE LOCAL: substituir pelo ID do usuário autenticado quando a autenticação estiver integrada.

type Alternative = { id: string; text: string };
type Question = { id: string; position: number; statement: string; discipline: string; topic: string; difficulty: string; alternatives: Alternative[]; selectedOptionId: string | null };
type Metric = { tipo: string; disciplina: string; percentual: number };
type Trail = { disciplinaPrioritaria: string; assuntoPrioritario: string | null; nivelRecomendado: string; quantidadeRecomendada: number; justificativa: string };
type Result = { overallPercentage: number; level: string; recommendation: string; performances: Metric[]; trail: Trail | null };
const labels: Record<string, string> = { BASICO: 'Básico', INTERMEDIARIO: 'Intermediário', AVANCADO: 'Avançado' };

function Brand() { return <div className="brand"><b>⚖</b><span><strong>JurisSim</strong><small>Plataforma adaptativa para o Exame da OAB.</small></span></div>; }
function Sidebar() { return <aside><Brand /><nav>{[['⌂','Início'],['▤','Estudar'],['?','Questões'],['▥','Meu desempenho']].map(([i,t], n) => <button className={n === 0 ? 'active' : ''} key={t}><i>{i}</i>{t}</button>)}</nav><div className="nav-bottom"><button><i>♙</i>Meu perfil</button><button><i>⚙</i>Configurações</button><hr /><button><i>⇥</i>Sair</button></div></aside>; }

function App() {
  if (!sessionStorage.getItem('jurissim_token')) return <AuthGate />;
  const [id, setId] = useState<string>(); const [questions, setQuestions] = useState<Question[]>([]); const [index, setIndex] = useState(0); const [answer, setAnswer] = useState<string>(); const [result, setResult] = useState<Result>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const call = async <T,>(path: string, init?: RequestInit) => { const response = await fetch(`${api}${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${sessionStorage.getItem('jurissim_token') ?? ''}`, ...init?.headers } }); const body = await response.json(); if (!response.ok) throw new Error(body.message ?? 'Não foi possível concluir a operação.'); return body as T; };
  const start = async () => { setLoading(true); setError(''); try { const attempt = await call<{ id:string }>('/diagnostics', { method:'POST', body:JSON.stringify({ questionCount:30 }) }); const response = await call<{questions:Question[]}>(`/diagnostics/${attempt.id}/questions`); setId(attempt.id); setQuestions(response.questions); } catch(cause) { setError(cause instanceof Error ? cause.message : 'Erro inesperado.'); } finally { setLoading(false); } };
  const next = async () => { if (!id || !answer) return; setLoading(true); setError(''); try { await call(`/diagnostics/${id}/answers/${questions[index].id}`, { method:'PUT', body:JSON.stringify({ selectedOptionId:answer }) }); setAnswer(undefined); if (index + 1 < questions.length) { setIndex(index + 1); return; } await call(`/diagnostics/${id}/finalize`, {method:'POST'}); const diagnosticResult = await call<Result>(`/diagnostics/${id}/result`); const trailResponse = await call<{trail:Trail}>(`/diagnostics/${id}/trail`); setResult({ ...diagnosticResult, trail: trailResponse.trail }); } catch(cause) { setError(cause instanceof Error ? cause.message : 'Erro inesperado.'); } finally { setLoading(false); } };
  if (!id && !result) return <main className="landing"><section className="pitch"><Brand /><div className="pitch-text"><p>DIAGNÓSTICO INTELIGENTE</p><h1>Prepare-se para a OAB <em>no seu ritmo.</em></h1><span>Identifique suas dificuldades, pratique de forma personalizada e acompanhe sua evolução.</span></div><div className="stats"><div><b>6</b>Matérias</div><div><b>30</b>Questões autorais</div><div><b>3</b>Níveis</div></div></section><section className="entry"><div><p className="gold">JURISSIM · OAB</p><h2>Simulado Diagnóstico Inicial</h2><p className="muted">Descubra seu nível e receba uma trilha personalizada para começar a estudar.</p><article className="start-card"><b className="spark">✦</b><h3>Comece sua preparação</h3><p>As questões são obtidas do banco de dados e o seu resultado é calculado pela API.</p><button className="primary" disabled={loading} onClick={start}>{loading ? 'Preparando...' : 'Iniciar diagnóstico'} <b>→</b></button>{error && <small className="error">{error}</small>}</article><small className="footnote">Sem login nesta etapa do projeto.</small></div></section></main>;
  if (!result) { const question=questions[index]; return <div className="shell"><Sidebar /><main className="content"><header>Simulado diagnóstico <b>Olá, estudante!⌄</b></header><section className="page"><p className="gold">QUESTÃO {index+1} DE {questions.length}</p><div className="heading"><div><h1>Responda com calma.</h1><p>{question.discipline}{question.topic && ` · ${question.topic}`}</p></div><strong>{index+1}<small>/{questions.length}</small></strong></div><div className="progress"><i style={{width:`${(index+1)/questions.length*100}%`}} /></div><article className="question"><h2>{question.statement}</h2><div className="answers">{question.alternatives.map((alternative, alternativeIndex) => <label className={answer===alternative.id?'picked':''} key={alternative.id}><input type="radio" checked={answer===alternative.id} onChange={()=>setAnswer(alternative.id)} /><b>{String.fromCharCode(65 + alternativeIndex)}</b><span>{alternative.text}</span></label>)}</div><footer>{error && <span className="error">{error}</span>}<button className="primary" disabled={!answer||loading} onClick={next}>{loading?'Salvando...':index+1===questions.length?'Finalizar diagnóstico':'Próxima questão'} <b>→</b></button></footer></article></section></main></div>; }
  const metrics=result.performances.filter(metric=>metric.tipo==='DISCIPLINA'); const trail=result.trail; return <div className="shell"><Sidebar /><main className="content"><header>Resultado do diagnóstico <b>Olá, estudante!⌄</b></header><section className="page result"><p className="gold">DIAGNÓSTICO CONCLUÍDO</p><h1>Seu desempenho</h1><p className="muted">Veja seu ponto de partida para a preparação.</p><article className="summary"><div className="score"><b>{result.overallPercentage}%</b><small>de acertos</small></div><div><p className="gold">SEU NÍVEL ATUAL</p><h2>{labels[result.level]}</h2><p>{result.recommendation}</p></div></article><article className="panel"><h2>Desempenho por disciplina</h2>{metrics.map(metric=><div className="metric" key={metric.disciplina}><span>{metric.disciplina}</span><div><i style={{width:`${metric.percentual}%`}} /></div><b>{metric.percentual}%</b></div>)}</article>{trail && <article className="trail"><div><p className="gold">SUA TRILHA PERSONALIZADA</p><h2>{trail.disciplinaPrioritaria}</h2><p><b>Tópico prioritário:</b> {trail.assuntoPrioritario ?? 'Conteúdos gerais da disciplina'}</p><p><b>Nível recomendado:</b> {labels[trail.nivelRecomendado]}</p></div><strong>{trail.quantidadeRecomendada}<small>questões<br/>recomendadas</small></strong></article>}</section></main></div>;
}
createRoot(document.getElementById('root')!).render(<App />);
